### ISSUE TITLE
package_absent in provision.sh appears to not work as expected

### ISSUE THREAD

**Issue by JeanFred** [intracer/wlxjury#67]
None of the packages were installed in `provision.sh`

Steps to reproduce:
1. vagrant up

The script crashes as mysql cannot be found. All the package installation bits were skipped

(I circumvented this by changing for 
```
function package_absent() {
    return 0;
}
```
in order to force the installation of packages.

**Comment by intracer** [comment]
Yes, I added it after provisioning, so it happened to serve only one purpose: to prevent installation againg. Not all stackoverflow answers are equally good. 
I fixed it in https://github.com/intracer/wlxjury/blob/master/provision_centos.sh but not as a function
